version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - PYTHONDONTWRITEBYTECODE=1
      - API_HOST=app
    volumes:
      - ./domain_modelling:/app/domain_modelling
      - ./tests:/app/tests
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_USER=allocation
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
